// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBC6Nzn2TxJMd-ShswsOlFRVt6H7wo2mhY',
    appId: '1:53403270486:web:bc2cd4fd9e20ea2acbeaf7',
    messagingSenderId: '53403270486',
    projectId: 'hms-b05b9',
    authDomain: 'hms-b05b9.firebaseapp.com',
    storageBucket: 'hms-b05b9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBANmxHIm6ymaRiPRhx9bJqDjeJiuZqcNg',
    appId: '1:53403270486:android:bdec8fefeecea824cbeaf7',
    messagingSenderId: '53403270486',
    projectId: 'hms-b05b9',
    storageBucket: 'hms-b05b9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZgX5yvTEuB-qw2y49jPzxwM_EytdGtP4',
    appId: '1:53403270486:ios:4c9671aea960d312cbeaf7',
    messagingSenderId: '53403270486',
    projectId: 'hms-b05b9',
    storageBucket: 'hms-b05b9.appspot.com',
    iosBundleId: 'com.example.myFlutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZgX5yvTEuB-qw2y49jPzxwM_EytdGtP4',
    appId: '1:53403270486:ios:c05322d20b194e23cbeaf7',
    messagingSenderId: '53403270486',
    projectId: 'hms-b05b9',
    storageBucket: 'hms-b05b9.appspot.com',
    iosBundleId: 'com.example.myFlutterApp.RunnerTests',
  );
}
